spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-hidden-grass-aqoanzvi.c-8.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_OusabvTHX7Y9&sslmode=require}
    driver-class-name: org.postgresql.Driver

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.d ata.jpa.JpaRepositoriesAutoConfiguration